#!/usr/bin/env python3
"""Emit the derived quantities the B1 results table invites a reader to compute.

The results table prints per group macro F1 and the prose then cites a mean, a
spread and an external drop. Each of those is an arithmetic combination of cells
the reader performs by hand, which is the defect D106 names: the published
burstiness separation was computed that way and came out wrong, because the cells
had already been rounded for display.

Nothing here refits anything. The three quantities are derived from the stored
artifact at full precision, so they cannot disagree with the model run that
produced it, and they are written as their own fields so the prose has a source.

Usage:
    uv run python scripts/b1_derived_summary.py
"""

import json
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ml.documents import provenance_line
from ml.paths import ARTIFACT_DIR, ROOT

SOURCE = ARTIFACT_DIR / "b1_results.json"
OUT = ARTIFACT_DIR / "b1_derived.json"
DOC = ROOT / "docs" / "b1_derived.md"
STATE_GROUPS = ("group_a", "group_b", "group_c")
EXTERNAL = "group_d_external"


def macro_f1(results: dict, group: str) -> float:
    return float(results["option_a"][group]["macro avg"]["f1-score"])


def main() -> int:
    if not SOURCE.is_file():
        print(f"BLOCKED: {SOURCE} missing", file=sys.stderr)
        return 2
    results = json.loads(SOURCE.read_text())

    per_group = {g: macro_f1(results, g) for g in STATE_GROUPS}
    mean = statistics.fmean(per_group.values())
    spread = max(per_group.values()) - min(per_group.values())
    external = macro_f1(results, EXTERNAL)
    drop = mean - external

    payload = {
        "source": SOURCE.name,
        "state_group_macro_f1": {g: v for g, v in per_group.items()},
        "state_group_mean_macro_f1": mean,
        "state_group_spread_macro_f1": spread,
        "external_macro_f1": external,
        "external_drop_from_state_mean": drop,
        "drop_to_spread_ratio": drop / spread if spread else None,
    }
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    for name, value in payload.items():
        if isinstance(value, float):
            print(f"  {name}: {value:.6f}")

    lines = [
        "# B1 derived summary",
        "",
        "Regenerate: `uv run python scripts/b1_derived_summary.py`",
        provenance_line(__file__),
        "",
        "Generated by `scripts/b1_derived_summary.py`. Derived from",
        f"`ml/artifacts/{SOURCE.name}` at full precision, without refitting anything.",
        "",
        "| Quantity | Value |",
        "| --- | --- |",
        f"| state group mean macro F1 | {mean:.4f} |",
        f"| state group spread macro F1 | {spread:.4f} |",
        f"| external group macro F1 | {external:.4f} |",
        f"| external drop from the state mean | {drop:.4f} |",
        f"| drop as a multiple of the spread | {drop / spread:.2f} |",
        "",
        "Each of these is cited in prose and each was previously a subtraction a reader",
        "had to perform against cells already rounded for display. D106.",
        "",
    ]
    DOC.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} and {DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
