#!/usr/bin/env python3
"""Background land cover rates, the missing half of the 3a sensitivity check.

3a measured background rates for the flare and industrial radii but not for the
land cover rules, because land cover had not been sampled yet. Without it the
agricultural and wildfire shares have nothing to be compared against, and a rule
that simply reports the land cover of a random point would look like a result.

This samples ESA WorldCover at the same uniform probe points used in 3a, inside
Indian state polygons, and reports the class distribution. If the agricultural
weak label share is close to the background cropland share, the rule is keyed on
geography rather than on what is burning.

Usage:
    uv run python scripts/landcover_background.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import duckdb

from ml.paths import DUCKDB_PATH, ROOT, ensure_dir
from ml.reference.geo import install_geo
from ml.reference.landcover import (
    TileNotAvailableError,
    class_name,
    group_by_tile,
    sample_tile_remote,
)

OUT = ROOT / "docs" / "landcover_background.md"
SEED = 20260904
PROBE_COUNT = 4000

PROBES_SQL = f"""
CREATE OR REPLACE TEMP TABLE probes AS
WITH box AS (SELECT 68.0 AS w, 6.5 AS s, 97.5 AS e, 37.5 AS n),
candidates AS (
    SELECT w + (e - w) * random() AS lon, s + (n - s) * random() AS lat
    FROM box, range(0, {PROBE_COUNT * 6})
)
SELECT c.lon, c.lat FROM candidates c
WHERE EXISTS (
    SELECT 1 FROM ref_osm_admin a
    WHERE a.admin_level = '4' AND ST_Contains(a.geom, ST_Point(c.lon, c.lat))
)
LIMIT {PROBE_COUNT};
"""


def main() -> int:
    con = duckdb.connect(str(DUCKDB_PATH))
    install_geo(con)
    con.execute(f"SELECT setseed({(SEED % 1000) / 1000.0})")
    con.execute(PROBES_SQL)
    points = [
        (float(r[0]), float(r[1])) for r in con.execute("SELECT lon, lat FROM probes").fetchall()
    ]
    print(f"probe points inside Indian state polygons: {len(points)}", flush=True)

    codes: list[int | None] = [None] * len(points)
    grouped = group_by_tile(points)
    print(f"tiles to sample: {len(grouped)}", flush=True)
    missing_tiles: list[tuple[str, int]] = []
    for position, (name, indexes) in enumerate(sorted(grouped.items()), start=1):
        try:
            sampled = sample_tile_remote(name, [points[i] for i in indexes])
        except TileNotAvailableError:
            missing_tiles.append((name, len(indexes)))
            continue
        for index, code in zip(indexes, sampled, strict=True):
            codes[index] = code
        if position % 15 == 0:
            print(f"  {position}/{len(grouped)} tiles", flush=True)
    if missing_tiles:
        unsampled = sum(count for _, count in missing_tiles)
        print(
            f"\n{len(missing_tiles)} tiles are not published, leaving {unsampled} "
            f"probe points unsampled:",
            flush=True,
        )
        for name, count in missing_tiles:
            print(f"  {name} {count} points", flush=True)

    named = [class_name(code) for code in codes]
    total = len(named)
    counts: dict[str, int] = {}
    for value in named:
        key = value or "unsampled"
        counts[key] = counts.get(key, 0) + 1

    # Map land cover onto the weak label class the rule would assign, so the
    # comparison is like for like.
    def rule_class(cover: str | None) -> str:
        if cover == "cropland":
            return "agricultural"
        if cover in ("tree_cover", "shrubland", "grassland"):
            return "wildfire"
        return "neither"

    rule_counts: dict[str, int] = {}
    for value in named:
        key = rule_class(value)
        rule_counts[key] = rule_counts.get(key, 0) + 1

    print("\nbackground land cover distribution:")
    for name, count in sorted(counts.items(), key=lambda item: -item[1]):
        print(f"  {name:24s} {count:5d}  {count / total:6.2%}")

    print("\nbackground share of the land cover weak label classes:")
    for name, count in sorted(rule_counts.items(), key=lambda item: -item[1]):
        print(f"  {name:14s} {count:5d}  {count / total:6.2%}")

    lines = [
        "# Background land cover rates",
        "",
        "Regenerate: `uv run python scripts/landcover_background.py`",
        "",
        "Generated by `scripts/landcover_background.py`.",
        "",
        f"{total} probe points drawn uniformly inside Indian state polygons, seed {SEED},",
        "the same points used for the flare and industrial radius sensitivity in 3a.",
        "",
        "| Land cover class | Points | Share |",
        "|---|---|---|",
    ]
    for name, count in sorted(counts.items(), key=lambda item: -item[1]):
        lines.append(f"| {name} | {count} | {count / total:.2%} |")
    lines += [
        "",
        "## As weak label classes",
        "",
        "| Rule class | Points | Background share |",
        "|---|---|---|",
    ]
    for name, count in sorted(rule_counts.items(), key=lambda item: -item[1]):
        lines.append(f"| {name} | {count} | {count / total:.2%} |")
    lines += [
        "",
        "This is what a detection placed uniformly at random inside India would be",
        "labelled by the land cover rules alone. Compare it against the measured shares",
        "in `docs/label_distribution.md`. A ratio near 1 means the rule is reporting the",
        "land cover of the location rather than anything about the fire.",
        "",
    ]
    ensure_dir(OUT.parent)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"\nwritten to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
