#!/usr/bin/env python3
"""Recompute the weak label lift with GEM assets folded into the industrial rule.

Reported before and after so the trackers' contribution is attributable. Before is
OSM industrial polygons and EOG flares alone; after adds the GEM assets under
their operating windows.

Usage:
    uv run python scripts/lift_with_gem.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import duckdb

from ml.documents import provenance_line
from ml.labels.background import industrial_background
from ml.labels.weak import FLARE_RADIUS_M, INDUSTRIAL_RADIUS_M, label_from_distances
from ml.paths import ARTIFACT_DIR, DUCKDB_PATH, ROOT, ensure_dir

OUT = ROOT / "docs" / "lift_with_gem.md"

# Agricultural is the cropland share from scripts/landcover_background.py. Industrial
# is read from its measurement per definition and window year rather than copied, D122.
BACKGROUND = {
    "flare": 0.0,
    "agricultural": 0.4655,
    "wildfire, withdrawn rule": 0.4098,
}
WITHDRAWN = "wildfire, withdrawn rule"
ARTIFACT = ARTIFACT_DIR / "lift_with_gem.json"

WINDOWS = {
    "monsoon 2026": ("2026-06-06", "2026-09-03"),
    "burning season 2023": ("2023-10-01", "2023-11-30"),
    "burning season 2024": ("2024-10-01", "2024-11-30"),
}


def shares(con: duckdb.DuckDBPyConnection, start: str, end: str, with_gem: bool) -> dict:
    industrial = (
        "least(coalesce(c.industrial_m, 1e12), coalesce(g.gem_m_temporal, 1e12))"
        if with_gem
        else "coalesce(c.industrial_m, 1e12)"
    )
    rows = con.execute(
        f"""
        SELECT c.flare_m, {industrial} AS ind_m, c.landcover_class
        FROM detection_context c
        JOIN detections d USING (detection_id)
        LEFT JOIN detection_gem g USING (detection_id)
        WHERE c.state_name IS NOT NULL AND d.acq_date_ist BETWEEN ? AND ?
        """,
        [start, end],
    ).fetchall()
    counts: dict[str, int] = {}
    for flare_m, ind_m, cover in rows:
        weak = label_from_distances(
            None if flare_m is None else float(flare_m),
            None if ind_m is None or float(ind_m) > 1e11 else float(ind_m),
            cover,
        )
        counts[weak.label] = counts.get(weak.label, 0) + 1
        # The withdrawn wildfire rule still fires inside label_from_distances and
        # returns unlabelled with its rule text. Counting it keeps the lift that
        # justified withdrawing it measurable rather than a remembered number. D122.
        if "formerly the wildfire rule" in weak.rule:
            counts[WITHDRAWN] = counts.get(WITHDRAWN, 0) + 1
    total = len(rows)
    return {
        "total": total,
        "counts": counts,
        "shares": {k: v / total for k, v in counts.items()} if total else {},
    }


def lift_text(name: str, share: float, *, with_gem: bool, year: int) -> str:
    if name == "industrial":
        background = industrial_background(year=year, with_gem=with_gem)
    else:
        background = BACKGROUND.get(name)
    if background is None:
        return "n/a"
    if background == 0.0:
        return "unbounded"
    return f"{share / background:.2f}x"


def main() -> int:
    con = duckdb.connect(str(DUCKDB_PATH))
    lines = [
        "# Weak label lift with the GEM trackers included",
        "",
        "Regenerate: `uv run python scripts/lift_with_gem.py`",
        provenance_line(__file__),
        "",
        "Generated by `scripts/lift_with_gem.py`.",
        "",
        "Before is OSM industrial features and EOG flares alone. After adds the GEM",
        "power, coal mine, steel and cement assets, matched only where the asset was",
        f"operating on the detection's date. Radii unchanged: flare "
        f"{FLARE_RADIUS_M:.0f} m, industrial {INDUSTRIAL_RADIUS_M:.0f} m.",
        "",
    ]
    lifts: dict[str, dict] = {}
    for label, (start, end) in WINDOWS.items():
        before = shares(con, start, end, with_gem=False)
        after = shares(con, start, end, with_gem=True)
        if before["total"] == 0:
            continue
        print(f"\n=== {label}  n={before['total']} ===")
        header = f"  {'class':14s} {'before':>9s} {'after':>9s}"
        print(f"{header} {'lift before':>12s} {'lift after':>11s}")
        lines += [
            f"## {label}",
            "",
            f"{start} to {end}, {before['total']} detections inside an Indian state.",
            "",
            "| Class | Before | After | Lift before | Lift after |",
            "|---|---|---|---|---|",
        ]
        window_lifts: dict[str, dict[str, float | None]] = {}
        for name in ("industrial", "flare", "agricultural", WITHDRAWN, "unlabelled"):
            # A class the rules no longer assign is absent, not measured at zero.
            # Defaulting a missing share to 0.0 rendered wildfire as 0.00 percent at
            # 0.00x lift after the class was withdrawn, which reads as a measurement
            # of a class that is not being assigned at all. Failure class one. D113.
            assigned = name in before["shares"] or name in after["shares"]
            if not assigned:
                print(f"  {name:14s} {'not assigned':>9s}")
                lines.append(
                    f"| {name} | not assigned | not assigned | not assigned | not assigned |"
                )
                continue
            sb = before["shares"].get(name, 0.0)
            sa = after["shares"].get(name, 0.0)
            year = int(start[:4])
            lb = lift_text(name, sb, with_gem=False, year=year)
            la = lift_text(name, sa, with_gem=True, year=year)
            print(f"  {name:14s} {sb:9.2%} {sa:9.2%} {lb:>12s} {la:>11s}")
            lines.append(f"| {name} | {sb:.2%} | {sa:.2%} | {lb} | {la} |")
            window_lifts[name] = {
                "share_before": sb,
                "share_after": sa,
                "lift_before": float(lb[:-1]) if lb.endswith("x") else None,
                "lift_after": float(la[:-1]) if la.endswith("x") else None,
            }
        lifts[label] = window_lifts
        gained = after["counts"].get("industrial", 0) - before["counts"].get("industrial", 0)
        print(f"  industrial labels gained from GEM: {gained}")
        lines += ["", f"Industrial labels gained from the GEM trackers: {gained}.", ""]

    ensure_dir(OUT.parent)
    ARTIFACT.write_text(json.dumps(lifts, indent=2, sort_keys=True) + "\n")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"\nwritten to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
