#!/usr/bin/env python3
"""Measure how OSM industrial coverage varies across India.

Reference coverage over India is incomplete non randomly, and the propensity model
in phase 6 needs a measure of how it varies geographically. This is produced now,
against the same snapshot that produced the features, because running it later
against a newer snapshot would not be reproducible.

The unevenness is the finding. Nothing here is smoothed or interpolated.

Usage:
    uv run python scripts/osm_coverage_report.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import duckdb

from ml.paths import DUCKDB_PATH, ROOT, ensure_dir
from ml.reference.geo import install_geo

OUT = ROOT / "docs" / "osm_coverage.md"

STATE_SQL = """
WITH states AS (
    SELECT osm_id,
           coalesce(nullif(name_en, ''), name) AS state_name,
           geom,
           geo_area_km2(geom) AS area_km2
    FROM ref_osm_admin
    WHERE admin_level = '4'
      AND coalesce(nullif(name_en, ''), name) IS NOT NULL
),
hits AS (
    SELECT s.state_name,
           s.area_km2,
           count(i.osm_id) AS features
    FROM states s
    LEFT JOIN ref_osm_industrial i
      ON ST_Contains(s.geom, ST_Point(i.longitude, i.latitude))
    GROUP BY s.state_name, s.area_km2
)
SELECT state_name,
       features,
       round(area_km2) AS area_km2,
       round(1000.0 * features / nullif(area_km2, 0), 3) AS per_1000_km2
FROM hits
ORDER BY per_1000_km2 DESC NULLS LAST
"""

UNASSIGNED_SQL = """
SELECT count(*) FROM ref_osm_industrial i
WHERE NOT EXISTS (
    SELECT 1 FROM ref_osm_admin s
    WHERE s.admin_level = '4'
      AND ST_Contains(s.geom, ST_Point(i.longitude, i.latitude))
)
"""

TAG_SQL = """
SELECT tag_key || '=' || tag_value AS tag, count(*) AS n
FROM ref_osm_industrial GROUP BY 1 ORDER BY 2 DESC
"""

DISTRICT_SQL = """
WITH districts AS (
    SELECT coalesce(nullif(name_en, ''), name) AS subdistrict_name, geom
    FROM ref_osm_admin WHERE admin_level = '6'
),
hits AS (
    SELECT d.subdistrict_name, count(i.osm_id) AS features
    FROM districts d
    LEFT JOIN ref_osm_industrial i
      ON ST_Contains(d.geom, ST_Point(i.longitude, i.latitude))
    GROUP BY d.subdistrict_name
)
SELECT subdistrict_name, features FROM hits ORDER BY features DESC
"""


def ascii_only(value: str) -> str:
    """Strip characters the repository conventions prohibit from OSM name data."""
    # Codepoints, not literals, so this file does not itself trip the checker.
    replacements = {0x2013: "-", 0x2014: "-", 0x2018: "'", 0x2019: "'"}
    return value.translate(replacements)


def main() -> int:
    con = duckdb.connect(str(DUCKDB_PATH))
    install_geo(con)

    states = con.execute(STATE_SQL).fetchall()
    unassigned = int(con.execute(UNASSIGNED_SQL).fetchone()[0])
    tags = con.execute(TAG_SQL).fetchall()
    districts = con.execute(DISTRICT_SQL).fetchall()
    total = int(con.execute("SELECT count(*) FROM ref_osm_industrial").fetchone()[0])

    lines: list[str] = []
    lines.append("# OSM industrial coverage over India")
    lines.append("")
    lines.append("Generated by `scripts/osm_coverage_report.py`.")
    lines.append("")
    lines.append("Snapshot: Geofabrik India extract, 2026-09-02T20:20:51Z, sequence 4895.")
    lines.append("Tags: landuse=industrial, man_made=works, man_made=flare, power=plant.")
    lines.append("")
    lines.append(f"Total industrial features: {total}")
    lines.append(f"Features inside no admin_level 4 polygon: {unassigned}")
    lines.append("")
    lines.append("## By tag")
    lines.append("")
    lines.append("| Tag | Features |")
    lines.append("|---|---|")
    for tag, count in tags:
        lines.append(f"| `{tag}` | {count} |")
    lines.append("")
    lines.append("## By state, ordered by density")
    lines.append("")
    lines.append("Density is features per 1000 square kilometres. It is a ratio of two")
    lines.append("measured quantities, not a smoothed or modelled value.")
    lines.append("")
    lines.append("| State or union territory | Features | Area km2 | Per 1000 km2 |")
    lines.append("|---|---|---|---|")
    for name, features, area, density in states:
        lines.append(f"| {ascii_only(str(name))} | {features} | {area} | {density} |")
    lines.append("")
    lines.append("## Top 25 sub districts by feature count")
    lines.append("")
    lines.append("| Sub district | Features |")
    lines.append("|---|---|")
    for name, features in districts[:25]:
        lines.append(f"| {ascii_only(str(name))} | {features} |")
    lines.append("")
    lines.append(
        "admin_level 6 in this extract is the sub district tier, tehsil, taluk or "
        "mandal, not the district tier. India has roughly 780 districts and the "
        f"extract carries {len(districts)} level 6 areas, so calling them districts "
        "would overstate the denominator by roughly eight times."
    )
    lines.append("")
    lines.append(
        f"Sub districts with zero industrial features: "
        f"{sum(1 for _, f in districts if f == 0)} of {len(districts)}"
    )
    lines.append("")

    ensure_dir(OUT.parent)
    OUT.write_text("\n".join(lines) + "\n")

    print(f"total features: {total}")
    print(f"unassigned to any state: {unassigned}")
    print(f"states reported: {len(states)}")
    print(
        f"sub districts reported: {len(districts)}, "
        f"{sum(1 for _, f in districts if f == 0)} with zero"
    )
    print(f"\nwritten to {OUT}")
    print("\ntop 10 by density:")
    for name, features, _area, density in states[:10]:
        print(f"  {ascii_only(str(name)):45s} {features:6d}  {density}")
    print("\nbottom 10 by density:")
    for name, features, _area, density in states[-10:]:
        print(f"  {ascii_only(str(name)):45s} {features:6d}  {density}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
