#!/usr/bin/env python3
"""Compare the weak label lift table and the IST diurnal profile across windows.

Two comparisons, both of which need care about what is being held constant.

Lift. The monsoon window is the annual minimum for crop residue burning, so the
land cover rules were measured where the phenomenon barely exists. Recomputing the
same lift on a burning season window says whether D21 was seasonal confounding or
a property of the rules.

Diurnal. VIIRS NOAA-21 carries no data before 2024-01-17, so the 2024 season has
four sensors and the 2023 season has three. Comparing raw counts across the two
years would report a 33 percent increase that is one extra satellite. Every year
on year comparison here is therefore restricted to the three sensors present in
both.

Usage:
    uv run python scripts/seasonal_comparison.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import duckdb

from ml.paths import DUCKDB_PATH, ROOT, ensure_dir

OUT = ROOT / "docs" / "seasonal_comparison.md"

# Background rates from the uniform probe points inside Indian state polygons.
# scripts/label_radius_sensitivity.py and scripts/landcover_background.py.
BACKGROUND = {
    "flare": 0.0,
    "industrial": 0.0175,
    "agricultural": 0.4655,
    "wildfire": 0.4098,
}

WINDOWS = {
    "monsoon 2026": ("2026-06-06", "2026-09-03"),
    "burning season 2023": ("2023-10-01", "2023-11-30"),
    "burning season 2024": ("2024-10-01", "2024-11-30"),
}

# Present in every window compared year on year. NOAA-21 is excluded from the
# diurnal comparison for that reason, and included in the lift tables, which are
# within window and therefore unaffected.
COMMON_SENSORS = ("MODIS", "VIIRS")
COMMON_SATELLITES = ("Terra", "Aqua", "N", "N20")


def lift_table(con: duckdb.DuckDBPyConnection, start: str, end: str) -> list[tuple]:
    return con.execute(
        """
        SELECT c.weak_label, count(*) AS n
        FROM detection_context c
        JOIN detections d USING (detection_id)
        WHERE c.state_name IS NOT NULL
          AND d.acq_date_ist BETWEEN ? AND ?
        GROUP BY 1 ORDER BY 2 DESC
        """,
        [start, end],
    ).fetchall()


def diurnal(con: duckdb.DuckDBPyConnection, start: str, end: str) -> dict[int, int]:
    placeholders = ", ".join(["?"] * len(COMMON_SATELLITES))
    rows = con.execute(
        f"""
        SELECT acq_hour_ist, count(*)
        FROM detections d
        JOIN detection_context c USING (detection_id)
        WHERE c.state_name IS NOT NULL
          AND d.acq_date_ist BETWEEN ? AND ?
          AND d.satellite IN ({placeholders})
        GROUP BY 1 ORDER BY 1
        """,
        [start, end, *COMMON_SATELLITES],
    ).fetchall()
    return {int(h): int(n) for h, n in rows}


def main() -> int:
    con = duckdb.connect(str(DUCKDB_PATH))
    lines: list[str] = [
        "# Seasonal comparison",
        "",
        "Generated by `scripts/seasonal_comparison.py`.",
        "",
    ]

    print("=== weak label lift by window, India assigned detections only ===")
    lines += [
        "## Weak label lift by window",
        "",
        "Lift is the measured share divided by the background share a uniformly",
        "placed detection inside India would pick up. A lift near or below 1 means the",
        "rule reports the land cover of the location rather than what is burning.",
        "",
    ]
    for label, (start, end) in WINDOWS.items():
        rows = lift_table(con, start, end)
        total = sum(n for _, n in rows)
        if total == 0:
            print(f"\n{label}: no detections ingested")
            lines += [f"### {label}", "", "Not ingested.", ""]
            continue
        print(f"\n{label}  ({start} to {end})  n={total}")
        print(f"  {'class':14s} {'share':>8s} {'background':>11s} {'lift':>10s}")
        lines += [
            f"### {label}",
            "",
            f"{start} to {end}, {total} detections inside an Indian state.",
            "",
            "| Class | Count | Share | Background | Lift |",
            "|---|---|---|---|---|",
        ]
        for name, count in rows:
            share = count / total
            background = BACKGROUND.get(name)
            if background is None:
                b_text, lift_text = "n/a", "n/a"
            elif background == 0.0:
                b_text, lift_text = "0.00%", "unbounded"
            else:
                b_text, lift_text = f"{background:.2%}", f"{share / background:.2f}x"
            print(f"  {name:14s} {share:8.2%} {b_text:>11s} {lift_text:>10s}")
            lines.append(f"| {name} | {count} | {share:.2%} | {b_text} | {lift_text} |")
        lines.append("")

    print("\n=== IST diurnal profile, three sensors present in both years ===")
    print("    MODIS Terra and Aqua, VIIRS S-NPP and NOAA-20. NOAA-21 excluded.")
    profiles = {
        label: diurnal(con, start, end)
        for label, (start, end) in WINDOWS.items()
        if label.startswith("burning")
    }
    if all(sum(p.values()) > 0 for p in profiles.values()):
        totals = {label: sum(p.values()) for label, p in profiles.items()}
        print(f"\n  {'hour':>5s}", end="")
        for label in profiles:
            print(f" {label[-4:]:>10s}", end="")
        print(f" {'2023 share':>11s} {'2024 share':>11s}")
        lines += [
            "## IST diurnal profile, burning seasons",
            "",
            "VIIRS NOAA-21 carries no data before 2024-01-17, so it is excluded from",
            "both years. The three sensors compared are MODIS Terra and Aqua, VIIRS",
            "S-NPP and VIIRS NOAA-20.",
            "",
            "Two seasons cannot establish a multi year trend. The published claim this",
            "responds to concerns a shift from 2020 to 2024, and 2020 is not ingested.",
            "",
            "| Hour IST | 2023 | 2024 | 2023 share | 2024 share |",
            "|---|---|---|---|---|",
        ]
        for hour in range(24):
            a = profiles["burning season 2023"].get(hour, 0)
            b = profiles["burning season 2024"].get(hour, 0)
            if a == 0 and b == 0:
                continue
            sa = a / totals["burning season 2023"]
            sb = b / totals["burning season 2024"]
            print(f"  {hour:5d} {a:10d} {b:10d} {sa:10.2%} {sb:10.2%}")
            lines.append(f"| {hour:02d}:00 | {a} | {b} | {sa:.2%} | {sb:.2%} |")
        lines.append("")
        for label, total in totals.items():
            lines.append(f"{label}: {total} detections on the common sensors.")
        lines.append("")
    else:
        print("  one of the burning seasons is not ingested yet")

    ensure_dir(OUT.parent)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"\nwritten to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
