import type { Manifest } from "@/lib/schema";

/**
 * Attribution renders in the interface, not only in the README. GEM and ESA
 * WorldCover are CC BY 4.0 and OpenStreetMap is ODbL, all of which require
 * attribution wherever the derived work is shown.
 */
export function AttributionFooter({ manifest }: { manifest: Manifest }) {
  return (
    <footer className="foot">
      <strong>Data sources and attribution</strong>
      <ul>
        {manifest.attribution.map((entry) => (
          <li key={entry.name}>
            <a href={entry.url} rel="noreferrer noopener" target="_blank">
              {entry.name}
            </a>
            {": "}
            {entry.detail}
          </li>
        ))}
      </ul>
      <p style={{ marginTop: "0.6rem" }}>
        Basemap tiles are supplied by whichever provider{" "}
        <code>NEXT_PUBLIC_BASEMAP_TILES</code> names, and carry that provider&apos;s
        own notice above. The underlying map data is copyright OpenStreetMap
        contributors, ODbL 1.0, whoever serves the tiles. This console displays
        precomputed results and runs no model. Generated by{" "}
        <code>{manifest.generatedBy}</code>.
      </p>
    </footer>
  );
}
